### ISSUE TITLE
Windows Friendly

### ISSUE THREAD

**Issue by nummi** [edgecase/git_immersion#10]
A majority of visitors are on Windows — what can we do to help them out? All the shell commands are currently for *nix.

Also, we do we need to have Ruby as a dependency?

**Comment by bsherwin** [comment]
@nummi Can you be more specific on what doesn't work on Windows? I have not found any commands that do not work in a Windows PowerShell environment.

The dependency on Ruby may seem to be unnecessary, but aside from doing the labs strictly in text files with text editor, there will need to be a dependency on some developer language environment. I think part of the value of this is that a user can see how to .gitignore files that are in managed packages. Ruby is easy to use/understand across platforms. Sure you could do node, python, etc. but to be fair, part of this decision is the legacy of Jim Weirich and his contributions and love of Ruby.

**Comment by aaronkelton** [comment]
I recently taught/guided students locally using this workshop and apart from myself navigating the Windows installation (it was my first rodeo), students were able to use their Windows machine just fine.

I could see how a student attempting this course by themselves _could_ get stuck on Lab 1, Step 4, especially if they're relatively new to the programming landscape. First, they have to find an appropriate installer and the choices can be bewildering to the untrained eye. Second, the download & installation have to complete successfully. When I was helping a student navigate the RubyInstaller, we actually didn't do it correctly the first time and had to redo it with a different option.

Maybe Step 4 should be broken out like Step 3 into a Unix/Mac section and a Windows section. (or really just a Windows side-note since Mac's already have Ruby). And for that Window's section, perhaps link directly to the RubyInstaller section: https://www.ruby-lang.org/en/documentation/installation/#rubyinstaller

**Comment by tonywok** [comment]
Going to close for now due to inactivity and the report involving the ability to teach the labs to students using windows. Feel free comment and I'll open back up!
