### ISSUE TITLE
Prepackaged repos should contain cloned_hello as well

### ISSUE THREAD

**Issue by gitqlt** [edgecase/git_immersion#17]
Lab_02 says: `repos — Prepackaged Git repositories so you can jump into the tutorial at any point. If you get stuck, just copy the desired lab into your working directory.`

However, from one point on it is not clear which of the two (three) work repos is recorded in `repos`. In the beginning it is the `hello` repo. Later it is either `cloned_hello` or `hello`. It would be better to have every subdirectory in the `repos` items, like
```
   repos/
       ...
       lab_10/
         hello/
       ...
       lab_40/
         hello/
         cloned_hello/
       ...
       lab_50/
         hello/
         cloned_hello/
         hello.git/
```
Anyway... what about using the name `snapshots` instead of `repos` for this stuff?

**Comment by tonywok** [comment]
@gitqlt I think snapshots might be a little misleading since each folder inside the `repos` directory is an actual git repository.

Admittedly it has been a while, but I recall the idea being that because each lab in the repos directory is a git repository, you can at any point restart the lab by copying the corresponding lab directory.

Thanks for filing the issue! I'm going to close for now. If you still feel strongly, I can re-open and further reconsider.
